id: P004170
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:58:03.403737
source_metadata:
  id: bdr:W1KG549
  title: ལམ་རིམ་བདེ་ལམ་དང་གསེར་གྱི་ཡང་ཞུན།
  author: ''
  volumes:
    165ab815caf64775be2a6377b38a56fc:
      image_group_id: I1KG554
      title: ''
      volume_number: 1
      total_pages: 108
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
