id: P004170
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG549
  title: ལམ་རིམ་བདེ་ལམ་དང་གསེར་གྱི་ཡང་ཞུན།
  author: ''
  volumes:
    165ab815caf64775be2a6377b38a56fc:
      image_group_id: I1KG554
      title: ''
      volume_number: 1
      total_pages: 108
